name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: build

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Dependencies
        run: go mod tidy

      - name: Install tools
        run: make install

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test ./...

      # - name: Run tests with coverage
      #   run: |
      #     mkdir -p coverage
      #     go test -covermode atomic -coverprofile=covprofile ./...
      #
      # - name: Install goveralls
      #   run: go install github.com/mattn/goveralls@latest
      #
      # - name: Send coverage
      #   env:
      #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: goveralls -coverprofile=covprofile -service=github

